# Generated by Django 5.0 on 2024-01-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userchoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoices',
            old_name='courseID',
            new_name='course_id',
        ),
    ]
