# Generated by Django 5.0 on 2024-02-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_userchoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
    ]
